module.exports = {
  API_RESULT_SUCCESS: "success",
  API_RESULT_ERROR: "error",

  ERROR_USERNAME_EXISTS: 'USERNAME_EXISTS',
  ERROR_INVALID_CAPTCHA: 'INVALID_CAPTCHA',
  ERROR_GENERIC: 'ERROR',
  ERROR_INVALID_TOKEN: 'INVALID_TOKEN',

  MONGO_ERROR_DUPLICATE_KEY: 11000
};
